/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\william project\\_myproject\\william-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-6f723474",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f723474").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-392a1b73",
    path: "/study/base/bind,call,apply.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-392a1b73").then(next)
    },
  },
  {
    name: "v-d4738c96",
    path: "/study/base/instanceof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d4738c96").then(next)
    },
  },
  {
    name: "v-2243eeae",
    path: "/life/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2243eeae").then(next)
    },
  },
  {
    path: "/life/index.html",
    redirect: "/life/"
  },
  {
    name: "v-64d8641f",
    path: "/study/base/extends.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64d8641f").then(next)
    },
  },
  {
    name: "v-5144fb11",
    path: "/study/base/new.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5144fb11").then(next)
    },
  },
  {
    name: "v-5e07a429",
    path: "/study/base/scope.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e07a429").then(next)
    },
  },
  {
    name: "v-292d0eb0",
    path: "/study/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-292d0eb0").then(next)
    },
  },
  {
    name: "v-77411801",
    path: "/study/base/proto.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77411801").then(next)
    },
  },
  {
    name: "v-3b0e9470",
    path: "/study/es6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b0e9470").then(next)
    },
  },
  {
    name: "v-47cc750a",
    path: "/study/handwrite/curry.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47cc750a").then(next)
    },
  },
  {
    name: "v-308bbec8",
    path: "/study/browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-308bbec8").then(next)
    },
  },
  {
    name: "v-39506a0a",
    path: "/study/handwrite/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39506a0a").then(next)
    },
  },
  {
    name: "v-0a81257b",
    path: "/study/handwrite/typeof.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a81257b").then(next)
    },
  },
  {
    name: "v-2d94510a",
    path: "/study/handwrite/debounce&throttle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d94510a").then(next)
    },
  },
  {
    name: "v-225cbe5d",
    path: "/study/handwrite/%E6%87%92%E5%8A%A0%E8%BD%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-225cbe5d").then(next)
    },
  },
  {
    path: "/study/handwrite/懒加载.html",
    redirect: "/study/handwrite/%E6%87%92%E5%8A%A0%E8%BD%BD.html"
  },
  {
    path: "/study/handwrite/懒加载.html",
    redirect: "/study/handwrite/%E6%87%92%E5%8A%A0%E8%BD%BD.html"
  },
  {
    name: "v-4e9a8a08",
    path: "/study/network.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e9a8a08").then(next)
    },
  },
  {
    name: "v-264d5b0e",
    path: "/study/optimization.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-264d5b0e").then(next)
    },
  },
  {
    name: "v-4b4de78a",
    path: "/study/handwrite/cloneDeep.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b4de78a").then(next)
    },
  },
  {
    name: "v-0fbe27b7",
    path: "/study/demo/rightMenu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fbe27b7").then(next)
    },
  },
  {
    name: "v-7269579b",
    path: "/study/react/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7269579b").then(next)
    },
  },
  {
    name: "v-436d8430",
    path: "/study/interview.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-436d8430").then(next)
    },
  },
  {
    name: "v-c7a6692e",
    path: "/study/vue/nextTick.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c7a6692e").then(next)
    },
  },
  {
    name: "v-7a6f26f4",
    path: "/study/target.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a6f26f4").then(next)
    },
  },
  {
    name: "v-07de77aa",
    path: "/study/ts.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07de77aa").then(next)
    },
  },
  {
    name: "v-766fe01d",
    path: "/study/vue/computed&watch.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-766fe01d").then(next)
    },
  },
  {
    name: "v-483490ef",
    path: "/study/vue/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-483490ef").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]