/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "william",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "lzh的BLOG",
        "tagline": "喜欢rap,beatbox,英雄联盟的酷酷boy",
        "actionText": "快速上手 →",
        "actionLink": "/study/target",
        "features": [
          {
            "title": "喜欢嘻哈的前端程序员",
            "details": "是个单身够,想要脱单,哪天你看不到这段话了,那说明我已经脱单了"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020 （可以根据实际情况写）"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-6f723474",
      "path": "/"
    },
    {
      "title": "call、apply、bind",
      "frontmatter": {},
      "regularPath": "/study/base/bind,call,apply.html",
      "relativePath": "study/base/bind,call,apply.md",
      "key": "v-392a1b73",
      "path": "/study/base/bind,call,apply.html",
      "headers": [
        {
          "level": 2,
          "title": "call",
          "slug": "call"
        },
        {
          "level": 2,
          "title": "apply",
          "slug": "apply"
        },
        {
          "level": 2,
          "title": "bind",
          "slug": "bind"
        }
      ]
    },
    {
      "title": "instanceof",
      "frontmatter": {},
      "regularPath": "/study/base/instanceof.html",
      "relativePath": "study/base/instanceof.md",
      "key": "v-d4738c96",
      "path": "/study/base/instanceof.html"
    },
    {
      "title": "william的日常",
      "frontmatter": {},
      "regularPath": "/life/",
      "relativePath": "life/README.md",
      "key": "v-2243eeae",
      "path": "/life/",
      "headers": [
        {
          "level": 3,
          "title": "2021年计划",
          "slug": "_2021年计划"
        }
      ]
    },
    {
      "title": "继承",
      "frontmatter": {},
      "regularPath": "/study/base/extends.html",
      "relativePath": "study/base/extends.md",
      "key": "v-64d8641f",
      "path": "/study/base/extends.html",
      "headers": [
        {
          "level": 2,
          "title": "1、原型链继承",
          "slug": "_1、原型链继承"
        },
        {
          "level": 2,
          "title": "2、经典继承(借用构造函数)",
          "slug": "_2、经典继承-借用构造函数"
        },
        {
          "level": 2,
          "title": "3、组合继承(最常用)",
          "slug": "_3、组合继承-最常用"
        },
        {
          "level": 2,
          "title": "4、寄生组合式继承",
          "slug": "_4、寄生组合式继承"
        }
      ]
    },
    {
      "title": "new",
      "frontmatter": {},
      "regularPath": "/study/base/new.html",
      "relativePath": "study/base/new.md",
      "key": "v-5144fb11",
      "path": "/study/base/new.html",
      "headers": [
        {
          "level": 2,
          "title": "new干了什么",
          "slug": "new干了什么"
        },
        {
          "level": 2,
          "title": "new的效果",
          "slug": "new的效果"
        },
        {
          "level": 2,
          "title": "new的实现",
          "slug": "new的实现"
        }
      ]
    },
    {
      "title": "作用域",
      "frontmatter": {},
      "regularPath": "/study/base/scope.html",
      "relativePath": "study/base/scope.md",
      "key": "v-5e07a429",
      "path": "/study/base/scope.html",
      "headers": [
        {
          "level": 2,
          "title": "1、词法作用域( lexical scoping ) / 静态作用域 和 动态作用域",
          "slug": "_1、词法作用域-lexical-scoping-静态作用域-和-动态作用域"
        },
        {
          "level": 2,
          "title": "2、执行上下文栈",
          "slug": "_2、执行上下文栈"
        }
      ]
    },
    {
      "title": "算法",
      "frontmatter": {},
      "regularPath": "/study/algorithm.html",
      "relativePath": "study/algorithm.md",
      "key": "v-292d0eb0",
      "path": "/study/algorithm.html",
      "headers": [
        {
          "level": 2,
          "title": "数据结构",
          "slug": "数据结构"
        },
        {
          "level": 2,
          "title": "链表",
          "slug": "链表"
        },
        {
          "level": 2,
          "title": "树",
          "slug": "树"
        }
      ]
    },
    {
      "title": "原型链理解",
      "frontmatter": {},
      "regularPath": "/study/base/proto.html",
      "relativePath": "study/base/proto.md",
      "key": "v-77411801",
      "path": "/study/base/proto.html"
    },
    {
      "title": "ES6",
      "frontmatter": {},
      "regularPath": "/study/es6.html",
      "relativePath": "study/es6.md",
      "key": "v-3b0e9470",
      "path": "/study/es6.html",
      "headers": [
        {
          "level": 2,
          "title": "1、let,const",
          "slug": "_1、let-const"
        },
        {
          "level": 2,
          "title": "2、class",
          "slug": "_2、class"
        },
        {
          "level": 2,
          "title": "3、module",
          "slug": "_3、module"
        }
      ]
    },
    {
      "title": "柯里化",
      "frontmatter": {},
      "regularPath": "/study/handwrite/curry.html",
      "relativePath": "study/handwrite/curry.md",
      "key": "v-47cc750a",
      "path": "/study/handwrite/curry.html",
      "headers": [
        {
          "level": 3,
          "title": "柯里化",
          "slug": "柯里化"
        }
      ]
    },
    {
      "title": "浏览器相关",
      "frontmatter": {},
      "regularPath": "/study/browser.html",
      "relativePath": "study/browser.md",
      "key": "v-308bbec8",
      "path": "/study/browser.html",
      "headers": [
        {
          "level": 2,
          "title": "1、缓存",
          "slug": "_1、缓存"
        },
        {
          "level": 2,
          "title": "2、本地存储",
          "slug": "_2、本地存储"
        },
        {
          "level": 2,
          "title": "3、输入URL到页面呈现发生了什么？",
          "slug": "_3、输入url到页面呈现发生了什么"
        },
        {
          "level": 2,
          "title": "XSS攻击",
          "slug": "xss攻击"
        },
        {
          "level": 2,
          "title": "CSRF攻击",
          "slug": "csrf攻击"
        }
      ]
    },
    {
      "title": "手写Promise",
      "frontmatter": {},
      "regularPath": "/study/handwrite/promise.html",
      "relativePath": "study/handwrite/promise.md",
      "key": "v-39506a0a",
      "path": "/study/handwrite/promise.html",
      "headers": [
        {
          "level": 3,
          "title": "手写Promise",
          "slug": "手写promise"
        }
      ]
    },
    {
      "title": "类型判断",
      "frontmatter": {},
      "regularPath": "/study/handwrite/typeof.html",
      "relativePath": "study/handwrite/typeof.md",
      "key": "v-0a81257b",
      "path": "/study/handwrite/typeof.html",
      "headers": [
        {
          "level": 3,
          "title": "类型判断",
          "slug": "类型判断"
        }
      ]
    },
    {
      "title": "防抖、节流",
      "frontmatter": {},
      "regularPath": "/study/handwrite/debounce&throttle.html",
      "relativePath": "study/handwrite/debounce&throttle.md",
      "key": "v-2d94510a",
      "path": "/study/handwrite/debounce&throttle.html",
      "headers": [
        {
          "level": 3,
          "title": "防抖、节流",
          "slug": "防抖、节流"
        }
      ]
    },
    {
      "title": "懒加载",
      "frontmatter": {},
      "regularPath": "/study/handwrite/%E6%87%92%E5%8A%A0%E8%BD%BD.html",
      "relativePath": "study/handwrite/懒加载.md",
      "key": "v-225cbe5d",
      "path": "/study/handwrite/%E6%87%92%E5%8A%A0%E8%BD%BD.html",
      "headers": [
        {
          "level": 3,
          "title": "懒加载",
          "slug": "懒加载"
        }
      ]
    },
    {
      "title": "计算机网络",
      "frontmatter": {},
      "regularPath": "/study/network.html",
      "relativePath": "study/network.md",
      "key": "v-4e9a8a08",
      "path": "/study/network.html",
      "headers": [
        {
          "level": 2,
          "title": "1、dns域名解析",
          "slug": "_1、dns域名解析"
        },
        {
          "level": 2,
          "title": "2、http,https",
          "slug": "_2、http-https"
        },
        {
          "level": 2,
          "title": "3、nginx",
          "slug": "_3、nginx"
        }
      ]
    },
    {
      "title": "性能优化",
      "frontmatter": {},
      "regularPath": "/study/optimization.html",
      "relativePath": "study/optimization.md",
      "key": "v-264d5b0e",
      "path": "/study/optimization.html",
      "headers": [
        {
          "level": 2,
          "title": "tree-shaking",
          "slug": "tree-shaking"
        }
      ]
    },
    {
      "title": "深浅克隆",
      "frontmatter": {},
      "regularPath": "/study/handwrite/cloneDeep.html",
      "relativePath": "study/handwrite/cloneDeep.md",
      "key": "v-4b4de78a",
      "path": "/study/handwrite/cloneDeep.html",
      "headers": [
        {
          "level": 3,
          "title": "深浅克隆",
          "slug": "深浅克隆"
        }
      ]
    },
    {
      "title": "右键菜单",
      "frontmatter": {},
      "regularPath": "/study/demo/rightMenu.html",
      "relativePath": "study/demo/rightMenu.md",
      "key": "v-0fbe27b7",
      "path": "/study/demo/rightMenu.html",
      "headers": [
        {
          "level": 3,
          "title": "右键菜单",
          "slug": "右键菜单"
        },
        {
          "level": 3,
          "title": "右键菜单样式",
          "slug": "右键菜单样式"
        },
        {
          "level": 3,
          "title": "在vuex中定义数据",
          "slug": "在vuex中定义数据"
        },
        {
          "level": 3,
          "title": "拦截右键事件处理指令参数",
          "slug": "拦截右键事件处理指令参数"
        },
        {
          "level": 3,
          "title": "在组件中使用指令",
          "slug": "在组件中使用指令"
        }
      ]
    },
    {
      "title": "基本概念",
      "frontmatter": {},
      "regularPath": "/study/react/react.html",
      "relativePath": "study/react/react.md",
      "key": "v-7269579b",
      "path": "/study/react/react.html",
      "headers": [
        {
          "level": 2,
          "title": "1、JSX语法",
          "slug": "_1、jsx语法"
        },
        {
          "level": 2,
          "title": "2、事件监听",
          "slug": "_2、事件监听"
        },
        {
          "level": 2,
          "title": "3、组件的state 和 setState",
          "slug": "_3、组件的state-和-setstate"
        },
        {
          "level": 2,
          "title": "4、配置组件的props",
          "slug": "_4、配置组件的props"
        },
        {
          "level": 2,
          "title": "5、state vs props",
          "slug": "_5、state-vs-props"
        },
        {
          "level": 2,
          "title": "6、前端应用状态管理",
          "slug": "_6、前端应用状态管理"
        },
        {
          "level": 2,
          "title": "1、组件挂载的生命周期",
          "slug": "_1、组件挂载的生命周期"
        },
        {
          "level": 2,
          "title": "2、ref 和 dom操作",
          "slug": "_2、ref-和-dom操作"
        },
        {
          "level": 2,
          "title": "1、高阶组件",
          "slug": "_1、高阶组件"
        },
        {
          "level": 2,
          "title": "2、Redux",
          "slug": "_2、redux"
        },
        {
          "level": 2,
          "title": "3、纯函数",
          "slug": "_3、纯函数"
        }
      ]
    },
    {
      "title": "面试合集",
      "frontmatter": {},
      "regularPath": "/study/interview.html",
      "relativePath": "study/interview.md",
      "key": "v-436d8430",
      "path": "/study/interview.html",
      "headers": [
        {
          "level": 2,
          "title": "ES6合集",
          "slug": "es6合集"
        },
        {
          "level": 2,
          "title": "算法面试题合集",
          "slug": "算法面试题合集"
        },
        {
          "level": 2,
          "title": "网易",
          "slug": "网易"
        }
      ]
    },
    {
      "title": "nextTick",
      "frontmatter": {},
      "regularPath": "/study/vue/nextTick.html",
      "relativePath": "study/vue/nextTick.md",
      "key": "v-c7a6692e",
      "path": "/study/vue/nextTick.html"
    },
    {
      "title": "学习任务",
      "frontmatter": {},
      "regularPath": "/study/target.html",
      "relativePath": "study/target.md",
      "key": "v-7a6f26f4",
      "path": "/study/target.html",
      "headers": [
        {
          "level": 3,
          "title": "1. js基础",
          "slug": "_1-js基础"
        },
        {
          "level": 3,
          "title": "2. 框架相关",
          "slug": "_2-框架相关"
        },
        {
          "level": 3,
          "title": "3. ES6",
          "slug": "_3-es6"
        },
        {
          "level": 3,
          "title": "4. TS",
          "slug": "_4-ts"
        },
        {
          "level": 3,
          "title": "5. 计算机网络",
          "slug": "_5-计算机网络"
        },
        {
          "level": 3,
          "title": "6. 浏览器相关",
          "slug": "_6-浏览器相关"
        },
        {
          "level": 3,
          "title": "7. 算法",
          "slug": "_7-算法"
        }
      ]
    },
    {
      "title": "ts",
      "frontmatter": {},
      "regularPath": "/study/ts.html",
      "relativePath": "study/ts.md",
      "key": "v-07de77aa",
      "path": "/study/ts.html",
      "headers": [
        {
          "level": 2,
          "title": "基础",
          "slug": "基础"
        }
      ]
    },
    {
      "title": "Computed和Watch",
      "frontmatter": {},
      "regularPath": "/study/vue/computed&watch.html",
      "relativePath": "study/vue/computed&watch.md",
      "key": "v-766fe01d",
      "path": "/study/vue/computed&watch.html"
    },
    {
      "title": "Vue3",
      "frontmatter": {},
      "regularPath": "/study/vue/vue3.html",
      "relativePath": "study/vue/vue3.md",
      "key": "v-483490ef",
      "path": "/study/vue/vue3.html",
      "headers": [
        {
          "level": 3,
          "title": "1、vue3中import的组件需要加上.vue后缀",
          "slug": "_1、vue3中import的组件需要加上-vue后缀"
        },
        {
          "level": 3,
          "title": "2、setup相关",
          "slug": "_2、setup相关"
        },
        {
          "level": 3,
          "title": "3、shallowReactive & shallowRef",
          "slug": "_3、shallowreactive-shallowref"
        },
        {
          "level": 3,
          "title": "4、provide & inject",
          "slug": "_4、provide-inject"
        },
        {
          "level": 3,
          "title": "5、watch & watchEffect",
          "slug": "_5、watch-watcheffect"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "文章",
        "items": [
          {
            "text": "日常",
            "link": "/life/"
          }
        ]
      },
      {
        "text": "掘金",
        "link": "https://juejin.im/user/8451823770045"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/ggwork"
      },
      {
        "text": "学习",
        "link": "/study/target"
      },
      {
        "text": "女朋友",
        "link": "/girlfriend/"
      }
    ],
    "sidebar": {
      "/study/": [
        {
          "title": "春起之苗",
          "children": [
            "target"
          ]
        },
        {
          "title": "js基础",
          "collapsable": true,
          "children": [
            "base/extends",
            "base/proto",
            "base/scope",
            "base/new",
            "base/bind,call,apply"
          ]
        },
        {
          "title": "手写系列",
          "children": [
            "handwrite/promise",
            "handwrite/debounce&throttle",
            "handwrite/curry",
            "handwrite/typeof",
            "handwrite/cloneDeep"
          ]
        },
        {
          "title": "Vue",
          "children": [
            "vue/computed&watch",
            "vue/nextTick",
            "vue/vue3"
          ]
        },
        "es6",
        "network",
        "browser",
        "optimization",
        "algorithm",
        {
          "title": "React",
          "children": [
            "react/react"
          ]
        },
        "ts",
        "interview"
      ],
      "/life/": [
        {
          "title": "生活琐事",
          "children": [
            "/life/"
          ]
        }
      ]
    },
    "sidebarDepth": 2,
    "lastUpdated": "Last Updated"
  }
}